config/routes.rb
Rails.application.routes.draw do
  resources :patients, path: ""

end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id                 :integer          not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  ur_number          :string(255)
#  medicare           :string(255)
#  credit_card        :string(255)
#  notes              :text
#  created_at         :datetime
#  updated_at         :datetime
#  masked_credit_card :string(255)
#

class Patient < ActiveRecord::Base

  attr_encrypted :credit_card,  random_iv: true
  attr_encrypted :medicare,  random_iv: true

  before_save do
    self.masked_credit_card = "#{'*' * 12}#{credit_card[12,15]}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :ur_number, :medicare, :credit_card, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medico</title>
  <%= stylesheet_link_tag "//yui.yahooapis.com/pure/0.5.0-rc-1/pure-min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="main" class="pure-g" style="width:960px; margin: 0 auto;">
    <div class="pure-u-1">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient, html: { class: "pure-form pure-form-aligned" }) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="pure-control-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="pure-control-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="pure-control-group">
      <%= f.label :ur_number %>
      <%= f.text_field :ur_number %>
    </div>
    <div class="pure-control-group">
      <%= f.label :medicare %>
      <%= f.text_field :medicare %>
    </div>
    <div class="pure-control-group">
      <%= f.label :credit_card %>
      <%= f.text_field :credit_card %>
    </div>
    <div class="pure-control-group">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </div>
    <div class="pure-controls actions">
      <%= f.submit class: "pure-button pure-button-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table class="pure-table pure-table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Ur number</th>
      <th>Medicare</th>
      <th>Credit card</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.ur_number %></td>
        <td><%= patient.medicare %></td>
        <td title="<%= patient.credit_card %>    <%= patient.encrypted_credit_card %>"><%= patient.masked_credit_card %></td>
        <td><%= patient.notes %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Ur number:</strong>
  <%= @patient.ur_number %>
</p>

<p>
  <strong>Medicare:</strong>
  <%= @patient.medicare %>
</p>

<p>
  <strong>Credit card:</strong>
  <%= @patient.credit_card %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @patient.notes %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>